typography_spectrum: 0.14177211304195225
content_rating:
  adult: false
color:
  brandStrength: 0.9537818997632712
  lightness: 0.7762217556592077
  saturation: 0.41163190943188965
  rhythmicContrast: 0.7418747371993959
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
layout_spectrum: 0.06616323906928301
author:
  name: Ryan Fickling
  url: www.ficklingmedia.com
  email: ryan@ficklingmedia.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d9f2f398-3e0d-4137-a233-b4b89045121c.jpg
name: 'Fickling Media, LLC'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/38532c33-5b0c-4ef1-964a-cbd4f09b86b5.jpg
title: Experience Video
