typography_spectrum: 0.14177211304195225
content_rating:
  adult: false
color:
  brandStrength: 0.9537818997632712
  lightness: 0.7762217556592077
  saturation: 0.41163190943188965
  rhythmicContrast: 0.7418747371993959
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
layout_spectrum: 0.06616323906928301
analytics:
  twitter: '#ficklingmedia'
author:
  name: Ryan Fickling
  url: 'https://thegrid.ai/ryan-fickling/'
  email: ryan@ficklingmedia.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/26ff54b8-59c4-4f65-8bed-ae3ed52b8370.jpg
name: 'Fickling Media, LLC'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/838c5942-2c27-4995-b02a-7bf3fa62f71d.jpg
title: 'Fickling Media, LLC'
description: Experience Video
